### ISSUE TITLE
Bot sold ADA for a loss?

### ISSUE THREAD

**Issue by 701709f91bb26fb01edb413fa5547b98** [ccxt/binance-trade-bot#221]
I've been running the bot for a couple of days and it appeared to be doing OK, but I just saw it sell ADA for less than the price it paid for it yesterday:

![](https://i.imgur.com/0u6tGrx.png)

Is this a bug? It doesn't seem like that should happen.

**Comment by panos4tw** [comment]
The bot doesn't trade based on FIAT/USDT/Bridge_Coin value, it trades on relative value to other coins with the goal of ending up with more coins. The bot did this trade because it would end up with more Qtum coins than it had in the past.

Things that might explain this decision: 1) Market was in a downtrend so even though it sold ADA for less, it was good a trade compared to other coins  2) Ada was just added on the coin list (or db was deleted) so it didn't have historical data to draw from
